### ISSUE TITLE
ExtensionQuery: Extend functionality for some aggregates

### ISSUE THREAD

**Issue by BriseLiese** [alica-labs/aspsuite#2]
There is currently no way to add an aggregate like: 
{maxTimestep(0..(N*N)) : fieldSize(N)} = 1.

It should be expanded to something like:
{query1(maxTimestep(0..(N*N))) : fieldSize(N)} = 1 :- externalquery1.
which is similar to what expandFactModuleProperty does with pure facts, but curly braces are not considered in that method and it requires this kind of construct to be added as a fact instead of a rule.

(expandRuleModuleProperty will currently expand it to
 {query1(maxTimestep(0..N)) : fieldSize(N), externalquery1} = 1.
which is a syntactically valid rule but doesn't have the intended behaviour)

**Comment by StephanOpfer** [comment]
I think we fixed it. See f27a3b9 and 2a3fd0c

**Comment by BriseLiese** [comment]
Tested, seems to work.
